name = "euro-keys"
main = "src/index.ts"
compatibility_date = "2024-12-06"

[[kv_namespaces]]
binding = "LOCKSMITH_KV"
id = "ad8b37aa307a45d0bcc2a833c2293499"

[[d1_databases]]
binding = "LOCKSMITH_DB"
database_name = "locksmith-db"
database_id = "216a2c05-31ad-4c86-9100-9d355da0336d"
