name = "euro-keys"
main = "src/index.ts"
compatibility_date = "2024-12-06"

[[kv_namespaces]]
binding = "LOCKSMITH_KV"
id = "ad8b37aa307a45d0bcc2a833c2293499"

[[d1_databases]]
binding = "LOCKSMITH_DB"
database_name = "locksmith-db"
database_id = "216a2c05-31ad-4c86-9100-9d355da0336d"

[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "euro-keys-assets"
preview_bucket_name = "euro-keys-assets-preview"

[ai]
binding = "AI"

[triggers]
crons = ["0 0 * * *"] # Run daily at midnight UTC

[vars]
DEV_EMAILS = "jeremysamuels17@gmail.com,jeremyandenmei@gmail.com,ben.samuels20@gmail.com"
# Cloudflare Analytics (Set these in your Cloudflare dashboard or .dev.vars for local dev)
CF_ANALYTICS_TOKEN = "OO4H6yv484kSfbB2D_HgnUhUXH-WBv67xQGq86vj" 
CF_ZONE_ID = "7bafb36a5620206fa00528e710e2b551"
